# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "kalcode"
repo = "isthereyanydeals-epic-json-importer"
token = ""  # Use GITHUB_TOKEN env var instead

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{%- for group, commits in commits | unique(attribute="message") | group_by(attribute="group") %}

### {{ group | striptags | trim | upper_first }}

{% for commit in commits -%}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }}
{% endfor %}
{%- endfor %}
"""
trim = true
output = "CHANGELOG.md"

[git]
conventional_commits = true
filter_unconventional = true
fail_on_unmatched_commit = true
protect_breaking_commits = true
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->ğŸš€ Features" },
    { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->âš¡ Performance" },
    { message = "^refactor", group = "<!-- 3 -->â™»ï¸ Refactoring" },
    { message = "^docs?", group = "<!-- 4 -->ğŸ“š Documentation" },
    { message = "^style", group = "<!-- 5 -->ğŸ¨ Styling" },
    { message = "^test", group = "<!-- 6 -->ğŸ§ª Tests" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", group = "<!-- 7 -->ğŸ”§ Chores" },
    { message = "^ci", group = "<!-- 8 -->ğŸ‘· CI/CD" },
    { message = "^build", group = "<!-- 9 -->ğŸ“¦ Build" },
    { message = "^revert", group = "<!-- 10 -->âª Reverts" },
]
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag="v0.0.1"
